# Generated by Django 5.0.6 on 2024-07-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
