# Generated by Django 5.0.6 on 2024-08-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0004_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='返信日時')),
                ('reply_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_from', to='post.post', verbose_name='返信内容')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='post.post', verbose_name='返信先')),
            ],
            options={
                'verbose_name': '返信',
                'verbose_name_plural': '返信',
                'db_table': 'comments',
            },
        ),
    ]
