# Generated by Django 5.0.6 on 2024-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name='メールアドレス')),
                ('auth_code', models.CharField(max_length=4, verbose_name='認証コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
            ],
            options={
                'verbose_name': '認証コード',
                'verbose_name_plural': '認証コード',
                'db_table': 'auth_codes',
            },
        ),
    ]
