# Generated by Django 5.0.6 on 2024-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_authcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='発行日時'),
        ),
    ]
