# Generated by Django 5.0.6 on 2024-05-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_authcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='ロック済み'),
        ),
        migrations.AddField(
            model_name='authcode',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='再試行回数'),
        ),
    ]
