# Generated by Django 5.0.6 on 2024-05-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_authcode_is_locked_authcode_retry_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcode',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='authcode',
            name='authentication_tries',
            field=models.IntegerField(default=0, verbose_name='認証試行回数'),
        ),
        migrations.AddField(
            model_name='authcode',
            name='email_resend_count',
            field=models.IntegerField(default=0, verbose_name='メールアドレス再送信回数'),
        ),
    ]
