# Generated by Django 5.0.6 on 2024-05-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_authcode_retry_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcode',
            name='email_resend_count',
        ),
        migrations.AddField(
            model_name='authcode',
            name='email_send_count',
            field=models.IntegerField(default=0, verbose_name='メールアドレス送信回数'),
        ),
    ]
