# Generated by Django 5.0.6 on 2024-05-26 05:30

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_authcode_email_send_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, validators=[common.validators.validate_email], verbose_name='メールアドレス'),
        ),
    ]
