# Generated by Django 5.0.6 on 2024-06-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_authcode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/user/', verbose_name='写真'),
        ),
    ]
