# Generated by Django 5.0.6 on 2024-06-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_username_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='image',
        ),
    ]
