class Strings {
  static const appName = 'White Cloud';
  static const login = 'ログイン';
  static const createAccount = 'アカウントを作成する';
  static const agree = "同意する";
  static const disAgree = "同意しない";
  static const or = "または";
  static const webviewError = "読み込み中にエラーが発生しました。";
  static const emailAddress = "メールアドレス";
  static const inputValidEmailAddress = "有効なメールアドレスを入力してください";
  static const sendEmailAddressPageTitle = "登録するメールアドレスを入力して、送信ボタンをタップしてください。";
  static const sendEmail = "送信する";
  static const sentAuthCodeByEmail = "認証コードを送信しました。";
  static const reSendAuthCode = "認証コードを再送信する";
  static const authenticate = "認証する";
  static const trimming = "トリミング";
  static const confirmAbortRegistration = "入力内容を破棄して、最初の画面に戻りますか？";
  static const yes = "はい";
  static const no = "いいえ";
  static const noteUserRegistration = "ユーザー情報を入力し、登録ボタンをタップしてください。";
  static const userName = "ユーザー名";
  static const introMessage = "メッセージ";
  static const aster = "*";
  static const register = "登録する";
  static const password = "パスワード";
  static const passwordErrorTooShort = "パスワードが短すぎます。8文字以上入力してください";
  static const passwordErrorInvalidFormat = "パスワードは少なくとも8文字以上で、大文字、小文字、数字、および特殊文字（@\$!%*?&）を含めてください。";
  static const createPostTitle = "新規投稿";
  static const createPostHint = "共有したいことを書こう";
  static const doPost = "投稿";
  static const followUser = "フォロー";
  static const searchInWhiteCloud = "White Cloudを検索";
  static const latest = "最新";
  static const user = "ユーザー";
  static const firstSearchPrefixMessage = "検索ワードを入力して、キーボードの";
  static const firstSearchSuffixMessage = "をタップしてください。";
  static const noSearchResults = "'%s'の検索結果はありません";
  static const noPosts = "表示できる投稿がありません。";
  static const errorHasOccurred = "エラーが発生しました。";
  static const retry = "もう一度実行";
  static const reply = "返信";
  static const replyTo = "に返信...";

  // エラー
  static const systemErrorMessage = "システムエラーが発生しました。しばらく待ってから再度お試しください。";
  static const timeoutErrorMessage = "申し訳ありませんが、サーバーへのリクエストがタイムアウトしました。しばらく待ってから再度お試しください。";
  static const connectionErrorMessage = "申し訳ありませんが、サーバーへの接続に失敗しました。インターネット接続を確認して、再度お試しください。";
  static const unexpectedErrorMessage = "システムエラーが発生しました。しばらく待ってから再度お試しください。";
}